

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ready On' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Ready On
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

# Pods for PodTest
pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'
end
